name: Django Messaging App CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u test_user --password=test_pass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt
          pip install unittest-xml-reporting
          pip install flake8 coverage

      - name: Run Flake8 (Linting)
        run: |
          echo "Running flake8 linting..."
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..15}; do
            if mysqladmin ping -h 127.0.0.1 -u test_user --password=test_pass --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Django migrations
        run: |
          python manage.py migrate --noinput

      - name: Run Tests with Coverage
        run: |
          mkdir -p test-reports
          coverage run manage.py test \
            --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner \
            --output-directory test-reports
          coverage xml -o coverage.xml
          coverage html -d coverage_html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            coverage_html/
            test-reports/
