# Generated by Django 5.2.3 on 2025-07-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_messages', to='messaging.message')),
            ],
        ),
    ]
