# Generated by Django 5.2.3 on 2025-07-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_edited_at_message_edited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
