# Generated by Django 5.2.3 on 2025-07-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_rename_reciever_message_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
