#!/bin/bash


echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

echo "Deploying Service..."
kubectl apply -f kubeservice.yaml

echo "Waiting for pods to be ready..."
kubectl rollout status deployment/django-messaging-blue
kubectl rollout status deployment/django-messaging-green

echo "Checking logs for blue pods..."
kubectl logs -l app=messaging-app,version=blue

echo "Checking logs for green pods..."
kubectl logs -l app=messaging-app,version=green

echo "You can now switch traffic to green using:"
echo 'kubectl patch service django-messaging-service -p "{\"spec\":{\"selector\":{\"app\":\"messaging-app\",\"version\":\"green\"}}}"'
